classDiagram
  
class Persona{
    -DNI                varchar 8  PK
    -nombre             varchar 30
    -apellido           varchar 30
    -telefono           varchar 20
    -email              varchar 30
    -fecha_nacimiento   date

    get crear    ()
    set crear    ()
    get modificar()
    set modificar()
    get borrar   ()
    set borrar   ()
}

class Empleado{
    -legajo         varchar 15 PK
    -DNI            varchar 8  FK
    -cod_categoria  int        FK

    get crear    ()
    set crear    ()
    get modificar()
    set modificar()
    get borrar   ()
    set borrar   ()
}

class Categoria{
    -cod_categoria   int        PK
    -descripcion     varchar 50 
    -salario_base    float

    get crear    ()
    set crear    ()
    get modificar()
    set modificar()
    get borrar   ()
    set borrar   ()
}

class Cliente{
    -id_cliente int         PK
    -DNI        varchar 8   FK

    get crear    ()
    set crear    ()
    get modificar()
    set modificar()
    get borrar   ()
    set borrar   ()
}

class Productos{
    -id_producto             int         PK
    -nombre_producto         varchar 30
    -descripcion_producto    varchar 50    
    -Precio                  float   
    -ubicacion               varchar 30 
    -stock_producto          int

    get crear    ()
    set crear    ()
    get modificar()
    set modificar()
    get borrar   ()
    set borrar   ()
}

class Proveedores{
    -id_proveedor            int         PK  
    -razon_social            varchar 20 
    -catalogo_proveedor      varchar 30

    get crear    ()
    set crear    ()
    get modificar()
    set modificar()
    get borrar   ()
    set borrar   ()
}

class Ventas{
    -id_venta           int PK
    -legajo             varchar 15 FK
    -id_cliente         int        FK
    -fecha_hora         datetime
    -metodo_pago        varchar 30

    get crear    ()
    set crear    ()
    get modificar()
    set modificar()
    get borrar   ()
    set borrar   ()
}

class Detalle_Ventas{
    -id_detalle_venta   int     PK
    -id_producto        int     FK
    -id_venta           int     FK
    -cantidad           int
    -precio_unit        float

    get crear    ()
    set crear    ()
    get modificar()
    set modificar()
    get borrar   ()
    set borrar   ()
}

class Pedido{
    -id_pedido              int     PK
    -id_proveedor           int     FK 
    -fecha_recepcion        date

    get crear    ()
    set crear    ()
    get modificar()
    set modificar()
    get borrar   ()
    set borrar   ()
}

class Detalle_Pedido{
    -id_detalle_pedido      int     PK
    -id_pedido              int     FK
    -id_producto            int     FK
    -cantidad_pedido        int
    -costo                  float

    get crear    ()
    set crear    ()
    get modificar()
    set modificar()
    get borrar   ()
    set borrar   ()
}
