classDiagram

class Ferreteria{
    -CIF                varchar PK        
    -DNI_dueno                varchar FK
    -direccion          varchar
    -numero_telefono    int
    -razon_social       varchar

    get crear    ()
    set crear    ()
    get modificar()
    set modificar()
    get borrar   ()
    set borrar   ()
}

class Persona{
    -DNI                varchar 8  PK
    -nombre             varchar 30
    -apellido           varchar 30
    -fecha_nacimiento   date

    get crear    ()
    set crear    ()
    get modificar()
    set modificar()
    get borrar   ()
    set borrar   ()
}

class Empleado{
    -legajo         varchar 15 PK
    -DNI            varchar 8  FK
    -cod_categoria  int        FK
    -clasifi        varchar 2  

    get crear    ()
    set crear    ()
    get modificar()
    set modificar()
    get borrar   ()
    set borrar   ()
}

class Categoria{
    -cod_categoria   varchar 15 PK
    -descripcion     varchar 50 

    get crear    ()
    set crear    ()
    get modificar()
    set modificar()
    get borrar   ()
    set borrar   ()
}

class Cliente{
    -DNI 

    get crear    ()
    set crear    ()
    get modificar()
    set modificar()
    get borrar   ()
    set borrar   ()
}

class Productos{


    get crear    ()
    set crear    ()
    get modificar()
    set modificar()
    get borrar   ()
    set borrar   ()
}

class Proveedores{


    get crear    ()
    set crear    ()
    get modificar()
    set modificar()
    get borrar   ()
    set borrar   ()
}

class Ventas{


    get crear    ()
    set crear    ()
    get modificar()
    set modificar()
    get borrar   ()
    set borrar   ()
}

class Detalle_Ventas{


    get crear    ()
    set crear    ()
    get modificar()
    set modificar()
    get borrar   ()
    set borrar   ()
}

class Pedido{


    get crear    ()
    set crear    ()
    get modificar()
    set modificar()
    get borrar   ()
    set borrar   ()
}

class Detalle_Pedido{


    get crear    ()
    set crear    ()
    get modificar()
    set modificar()
    get borrar   ()
    set borrar   ()
}

